---
title: "R Notebook"
output: html_notebook
---
```{r}
install.packages("glmnet", repos = "http://cran.us.r-project.org")
```

```{r}
library(glmnet)
```

```{r}
dataPath<-"./"
```

```{r}
data <- read.csv(paste(dataPath,"test_sample.csv",sep="/"),header=T,sep=" ")
```

```{r}
X<-data.matrix(data[,2:492])
Y<-data[,1]
dim(X)
length(Y)
```
```{r}
rSquared<-sapply(1:491,function(z) summary(lm(Y~.,data=data.frame(Y=Y,X[,1:z])))$r.squared)
N.orig<-min(which(rSquared > 0.9))
```

```{r}
XPCA<-prcomp(X, retx = TRUE)
```

```{r}
install.packages("relaimpo")
```
```{r}
library(relaimpo)
```
```{r}
m10.PCA<-lm(Y~.,data=data.frame(Y=Y,XPCA$x))
metrics.PCA <- calc.relimp(m10.PCA, type = c("first"))
```

```{r}
first.PCA.rank<-metrics.PCA@first.rank
orderedFactors<-XPCA$x[,order(first.PCA.rank)]
rSquaredOrderedPCA<-sapply(1:N.orig,function(z) summary(lm(Y~.,data=data.frame(Y=Y,orderedFactors[,1:z])))$r.squared)
N.PCA<-min(which(rSquaredOrderedPCA > 0.9))
mdr<-N.orig-N.PCA
rSqBest<-rSquaredOrderedPCA[N.OrderedPCA]
```



